-- MySQL Script generated by MySQL Workbench
-- Mon Aug 15 15:59:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Aerolinea_Examen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Aerolinea_Examen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Aerolinea_Examen` DEFAULT CHARACTER SET utf8 ;
USE `Aerolinea_Examen` ;

-- -----------------------------------------------------
-- Table `Aerolinea_Examen`.`Aerolinea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aerolinea_Examen`.`Aerolinea` (
  `IdVuelo` VARCHAR(100) NOT NULL,
  `Origen` VARCHAR(100) NOT NULL,
  `Destino` VARCHAR(100) NOT NULL,
  `Avion` VARCHAR(100) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Piloto` VARCHAR(100) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`IdVuelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Aerolinea_Examen`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aerolinea_Examen`.`Usuario` (
  `Codigo` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `EstaActivo` TINYINT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
